# Statistics

- Uses numpy for random number generation (assuming this is not cheating?)

In [8]:
import numpy as np

## Arg Checker

#### Limitation: doesn't check values are of correct format

In [38]:
def _valid_input(args):
    if None in args:
        print("Input params incorrect - try again!")
        print("\nRequirements:")
        print("\tnormal parmas: num_samples, mean, std_dev")
        print("\tpoisson parmas: num_samples, num_trials, prob_success")
        print("\tbinomial parmas: num_samples, lam")
        return False
    return True

## Generator

In [48]:
def random_number_generator(num_samples, distribution, mean=None, std_dev=None, lam=None, num_trials=None, prob_success=None):
    """
    Draws random numbers from a given distribution
    
    :param num_samples: num of numbers to generate [int: required]
    :param distribution: normal|poisson|binomial [string: required]
    :param mean: mean [float: required for normal]
    :param std_dev: std dev [float: required for normal]
    :param lam: ave num successes >0 [float: required for poisson]
    :param num_trials: num_trials > 0 [int: required for binomial]
    :param prob_success: 0 < prob(success) < 1  [float: required for binomial]
    :return: numpy array of shape (num_samples,)
    """

    if distribution.lower() == 'normal':
        if _valid_input(args=[num_samples, mean, std_dev]):
            return np.random.normal(loc=mean, scale=std_dev, size=num_samples)

    elif distribution.lower() == 'poisson':
        if _valid_input(args=[num_samples, lam]):
            return np.random.poisson(lam=lam, size=num_samples)
    
    elif distribution.lower() == 'binomial':
        if _valid_input(args=[num_samples, num_trials, prob_success]):
            return np.random.binomial(n=num_trials, p=prob_success, size=num_samples)
    
    else:
        print("Hmm... I don't know this {} distribution?".format(distribution))

# Examples

### Normal

In [58]:
random_number_generator(num_samples=10, 
                        distribution='normal', 
                        mean=-23, 
                        std_dev=100)

array([  66.44698692,  -50.43139836,  -35.10990622,  -35.33047281,
         10.0480059 ,  -42.96690023,  180.18237238,  -65.74089907,
       -212.05461128,  120.94415897])

## Poisson

In [56]:
random_number_generator(num_samples=10, 
                        distribution='poisson',
                        lam=90)

array([ 77,  94,  70,  91,  87, 113,  99,  89,  91,  89])

## Binomial

In [57]:
random_number_generator(num_samples=10, 
                        distribution='binomial',
                        prob_success=0.3,
                        num_trials=13)

array([5, 3, 3, 5, 5, 3, 7, 1, 2, 4])